use core_model::settings::HyprlandSettings;

use crate::types::{FixtureSource, HyprlandExportResult, HyprlandFixtureResult, ReloadOutput};

/// Contenido del fixture embebido en el binario.
const FIXTURE_CONTENT: &str = include_str!("../../../fixtures/hyprland/hyprland.conf");

/// Carga el fixture de Hyprland desde el binario.
///
/// LIMITATION (fase 1): Solo devuelve el contenido del fixture embebido.
/// No lee ni modifica archivos del sistema real.
pub fn load_fixture() -> HyprlandFixtureResult {
    HyprlandFixtureResult {
        content: FIXTURE_CONTENT.to_string(),
        source: FixtureSource::Embedded,
    }
}

/// Genera el contenido de hyprland.conf a partir de `HyprlandSettings`.
///
/// LIMITATION (fase 1): Solo genera el bloque `general {}` y `decoration {}`.
/// No escribe en disco. No recarga Hyprland. El formato no es un parser completo;
/// es una generación directa de los campos soportados por el core-model.
pub fn export_from_settings(s: &HyprlandSettings) -> HyprlandExportResult {
    let active = s.active_border_color.trim_start_matches('#');
    let inactive = s.inactive_border_color.trim_start_matches('#');

    let mut lines: Vec<String> = Vec::new();
    lines.push("# Generated by Linux Control Center — do not edit manually".into());
    lines.push("# PHASE 1: Not applied to real system".into());
    lines.push(String::new());
    lines.push("general {".into());
    lines.push(format!("    gaps_in = {}", s.gaps_in));
    lines.push(format!("    gaps_out = {}", s.gaps_out));
    lines.push(format!("    border_size = {}", s.border_size));
    lines.push(format!("    col.active_border = rgba({}ff)", active));
    lines.push(format!("    col.inactive_border = rgba({}ff)", inactive));
    lines.push("    layout = dwindle".into());
    lines.push("}".into());
    lines.push(String::new());
    lines.push("decoration {".into());
    lines.push(format!("    rounding = {}", s.rounding));
    lines.push("    blur {".into());
    lines.push(format!("        enabled = {}", s.blur_enabled));
    lines.push(format!("        size = {}", s.blur_size));
    lines.push(format!("        passes = {}", s.blur_passes));
    lines.push("    }".into());
    lines.push("}".into());
    lines.push(String::new());
    lines.push("animations {".into());
    lines.push(format!("    enabled = {}", s.animations_enabled));
    lines.push("}".into());

    HyprlandExportResult { content: lines.join("\n") + "\n" }
}

/// Ejecuta `hyprctl reload` para que Hyprland recargue su configuración en vivo.
///
/// - Nunca hace panic: si `hyprctl` no está en PATH o Hyprland no está corriendo,
///   devuelve `ReloadOutput { ok: false, output: "…" }`.
/// - No hay timeout explícito: el socket de Hyprland responde en < 200 ms normalmente.
///   Si se necesita timeout en producción, envolver con `std::thread::spawn` + join con deadline.
pub fn reload_compositor() -> ReloadOutput {
    match std::process::Command::new("hyprctl").arg("reload").output() {
        Ok(out) => ReloadOutput {
            ok: out.status.success(),
            output: format!(
                "{}{}",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr)
            )
            .trim()
            .to_string(),
        },
        Err(e) => ReloadOutput {
            ok: false,
            output: format!("hyprctl not available: {e}"),
        },
    }
}
