use core_model::settings::RofiSettings;

use crate::types::{FixtureSource, RofiExportResult, RofiFixtureResult};

/// Contenido del fixture embebido en el binario.
const FIXTURE_CONTENT: &str = include_str!("../../../fixtures/rofi/config.rasi");

fn visual_block_from_settings(s: &RofiSettings) -> String {
    let el_r = (s.border_radius / 2).clamp(2, 12);
    format!(
        r#"
* {{
    bg:     {bg};
    fg:     {fg};
    accent: {accent};
    border: {border};

    background-color: transparent;
    text-color:       @fg;
}}

window {{
    background-color: @bg;
    border:           2px solid @border;
    border-radius:    {br}px;
    width:            480px;
}}

inputbar {{
    children:         [prompt, entry];
    background-color: {input_bg};
    border-radius:    6px;
    padding:          6px 10px;
    margin:           8px;
}}

prompt {{
    text-color: @accent;
    margin:     0 8px 0 0;
}}

entry {{
    placeholder: "Search…";
}}

listview {{
    padding:    4px 8px;
    scrollbar:  false;
}}

element {{
    padding:       6px 8px;
    border-radius: {el_r}px;
}}

element selected {{
    background-color: @accent;
    text-color:       @bg;
}}
"#,
        bg = s.vis_bg,
        fg = s.vis_fg,
        accent = s.vis_accent,
        border = s.vis_border,
        br = s.border_radius,
        input_bg = s.vis_input_bg,
        el_r = el_r,
    )
}

/// Carga el fixture de Rofi desde el binario.
///
/// LIMITATION: Solo devuelve el contenido del fixture embebido.
/// No lee ni modifica archivos del sistema real.
pub fn load_fixture() -> RofiFixtureResult {
    RofiFixtureResult {
        content: FIXTURE_CONTENT.to_string(),
        source: FixtureSource::Embedded,
    }
}

/// Genera el contenido de config.rasi a partir de `RofiSettings`.
///
/// Genera `configuration {{}}` y bloques visuales a partir de `RofiSettings`
/// (colores en `vis_*` y `border_radius`).
pub fn export_from_settings(s: &RofiSettings) -> RofiExportResult {
    let show_icons = if s.show_icons { "true" } else { "false" };

    let mut lines: Vec<String> = Vec::new();
    lines.push("# Generated by Linux Control Center — do not edit manually".into());
    lines.push("# LIMITATION: Not applied to real system. Theme field reserved for future phase.".into());
    lines.push(String::new());
    lines.push("configuration {".into());
    lines.push(format!("    modi:               \"{}\";", s.modi));
    lines.push(format!("    show-icons:     {};", show_icons));
    lines.push(format!("    icon-theme:         \"{}\";", s.icon_theme));
    lines.push(format!("    display-drun:       \"{}\";", s.display_drun));
    lines.push(format!("    display-run:        \"{}\";", s.display_run));
    lines.push(format!("    display-window:     \"{}\";", s.display_window));
    lines.push(format!(
        "    drun-display-format: \"{}\";",
        s.drun_display_format
    ));
    lines.push(format!("    font:               \"{}\";", s.font));
    lines.push("}".into());

    let content = lines.join("\n") + "\n" + &visual_block_from_settings(s);
    RofiExportResult { content }
}
