use core_model::settings::WaybarSettings;

use crate::types::{FixtureSource, WaybarExportResult, WaybarFixtureResult};

/// Contenido del fixture embebido en el binario.
const FIXTURE_CONTENT: &str = include_str!("../../../fixtures/waybar/config.jsonc");

/// Carga el fixture de Waybar desde el binario.
///
/// LIMITATION (fase 1): Solo devuelve el contenido del fixture embebido.
/// No lee ni modifica archivos del sistema real.
pub fn load_fixture() -> WaybarFixtureResult {
    WaybarFixtureResult {
        content: FIXTURE_CONTENT.to_string(),
        source: FixtureSource::Embedded,
    }
}

/// Genera el contenido de config.jsonc a partir de `WaybarSettings`.
///
/// LIMITATION (fase 1): Genera JSON manualmente; no escribe en disco ni recarga waybar.
/// Solo cubre los campos del core-model. Campos avanzados (estilos CSS, etc.) no están soportados.
pub fn export_from_settings(s: &WaybarSettings) -> WaybarExportResult {
    let modules_left = format_module_array(&s.modules_left);
    let modules_center = format_module_array(&s.modules_center);
    let modules_right = format_module_array(&s.modules_right);

    let mut lines: Vec<String> = Vec::new();
    lines.push("{".into());
    lines.push("    \"layer\": \"top\",".into());
    lines.push(format!("    \"position\": \"{}\",", s.position));
    lines.push(format!("    \"height\": {},", s.height));
    lines.push(format!("    \"modules-left\": {},", modules_left));
    lines.push(format!("    \"modules-center\": {},", modules_center));
    lines.push(format!("    \"modules-right\": {}", modules_right));
    lines.push("}".into());

    WaybarExportResult { content: lines.join("\n") + "\n" }
}

/// Genera `style.css` para Waybar (GTK CSS) a partir de los colores del modelo.
///
/// Cubre ventana, workspaces y módulos comunes; el usuario puede ampliar el archivo a mano.
pub fn export_style_from_settings(s: &WaybarSettings) -> WaybarExportResult {
    let r = 6u8;
    let content = format!(
        r#"/* Generated by Linux Control Center — theme colors */
* {{
  border: none;
  border-radius: 0;
}}

window#waybar {{
  background-color: {bg};
  color: {fg};
}}

#workspaces button {{
  padding: 0 10px;
  margin: 4px 2px;
  border-radius: {r}px;
  background-color: {mod_bg};
  color: {fg};
}}

#workspaces button.active {{
  background-color: {accent};
  color: {bg};
}}

#clock,
#cpu,
#memory,
#battery,
#network,
#pulseaudio,
#tray,
#window {{
  padding: 0 12px;
  margin: 4px 2px;
  border-radius: {r}px;
  background-color: {mod_bg};
  color: {fg};
}}

tooltip {{
  background-color: {mod_bg};
  color: {fg};
  border: 1px solid {accent};
}}
"#,
        bg = s.bar_background,
        fg = s.bar_foreground,
        mod_bg = s.module_background,
        accent = s.accent,
        r = r,
    );

    WaybarExportResult { content }
}

fn format_module_array(modules: &[String]) -> String {
    let inner = modules
        .iter()
        .map(|m| format!("\"{}\"", m))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{}]", inner)
}
