/**
 * Re-exports auto-generated TypeScript bindings from core-model Rust types.
 *
 * The interfaces are generated by ts-rs. To regenerate them, run:
 *   cargo test --package core-model export_bindings
 *
 * Only `defaultSettings` is maintained manually here; it mirrors the Rust
 * `AppSettings::default()` impl and must be kept in sync with it.
 */
export type {
  AppSettings,
  AppearanceSettings,
  HyprlandSettings,
  WaybarSettings,
  RofiSettings,
  ProfileMetadata,
  SettingsProfile,
} from "./generated";

import type { AppSettings } from "./generated";

/** Settings por defecto — espejo del Default impl de Rust */
export const defaultSettings: AppSettings = {
  appearance: {
    theme: "dark",
    accent_color: "#88c0d0",
    font_family: "Inter",
    font_size: 11,
    icon_theme: "Papirus",
    cursor_theme: "Adwaita",
    cursor_size: 24,
  },
  hyprland: {
    gaps_in: 4,
    gaps_out: 8,
    border_size: 2,
    active_border_color: "#88c0d0",
    inactive_border_color: "#4c566a",
    rounding: 8,
    animations_enabled: true,
    blur_enabled: true,
    blur_size: 4,
    blur_passes: 2,
  },
  waybar: {
    position: "top",
    height: 32,
    modules_left: ["hyprland/workspaces", "hyprland/window"],
    modules_center: ["clock"],
    modules_right: ["network", "cpu", "memory", "battery", "tray"],
  },
  rofi: {
    theme: "nord",
    modi: "drun,run,window",
    font: "Inter 11",
    show_icons: true,
    icon_theme: "Papirus",
    display_drun: "Apps",
    display_run: "Run",
    display_window: "Windows",
    drun_display_format: "{name}",
  },
};
