/**
 * Re-exports auto-generated TypeScript bindings from core-model Rust types.
 *
 * The interfaces are generated by ts-rs. To regenerate them, run:
 *   cargo test --package core-model export_bindings
 *
 * Only `defaultSettings` is maintained manually here; it mirrors the Rust
 * `AppSettings::default()` impl and must be kept in sync with it.
 */
export type {
  AppSettings,
  AppearanceSettings,
  HyprlandBind,
  HyprlandInputSettings,
  HyprlandKeyboardSettings,
  HyprlandSettings,
  HyprlandWindowRule,
  HyprlandWindowSettings,
  WaybarSettings,
  RofiSettings,
  ProfileMetadata,
  SettingsProfile,
} from "./generated";

import type { AppSettings } from "./generated";

/** Settings por defecto — espejo del Default impl de Rust */
export const defaultSettings: AppSettings = {
  appearance: {
    theme: "dark",
    accent_color: "#88c0d0",
    font_family: "Inter",
    font_size: 11,
    icon_theme: "Papirus",
    cursor_theme: "Adwaita",
    cursor_size: 24,
  },
  hyprland: {
    gaps_in: 4,
    gaps_out: 8,
    border_size: 2,
    active_border_color: "#88c0d0",
    inactive_border_color: "#4c566a",
    rounding: 8,
    animations_enabled: true,
    blur_enabled: true,
    blur_size: 4,
    blur_passes: 2,
    keyboard: { binds: [] },
    windows: { rules: [] },
    input: {
      kb_layout: "us",
      kb_variant: "",
      kb_options: "",
      mouse_sensitivity: 0,
      natural_scroll: false,
      touchpad_natural_scroll: false,
    },
  },
  waybar: {
    position: "top",
    height: 32,
    bar_background: "#2e3440",
    bar_foreground: "#eceff4",
    module_background: "#3b4252",
    accent: "#88c0d0",
    modules_left: ["hyprland/workspaces", "hyprland/window"],
    modules_center: ["clock"],
    modules_right: ["network", "cpu", "memory", "battery", "tray"],
  },
  rofi: {
    theme: "nord",
    modi: "drun,run,window",
    font: "Inter 11",
    show_icons: true,
    icon_theme: "Papirus",
    display_drun: "Apps",
    display_run: "Run",
    display_window: "Windows",
    drun_display_format: "{name}",
    vis_bg: "#2e3440",
    vis_fg: "#d8dee9",
    vis_accent: "#88c0d0",
    vis_border: "#4c566a",
    vis_input_bg: "#3b4252",
    border_radius: 8,
  },
  wallpaper: {
    last_applied_wallpaper_id: null,
    last_successful_apply_at: null,
  },
};
