use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Destino de escritura — allowlist cerrada (sin rutas arbitrarias).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../apps/desktop/src/types/generated/")]
pub enum WriteTarget {
    /// Archivo managed por Linux Control Center (NO es el orquestador principal).
    /// `~/.config/hypr/generated/linux-control-center.conf`
    HyprlandGeneratedConfig,
    /// Archivo principal de Hyprland (orquestador). **Nunca** debe sobrescribirse completo
    /// por la app; solo se permite insertar (idempotentemente) un `source = ...` si falta.
    /// `~/.config/hypr/hyprland.conf`
    HyprlandMainConfig,
    WaybarConfig,
    /// `~/.config/waybar/style.css` — estilos generados (p. ej. Theme Manager).
    WaybarStyle,
    RofiConfig,
}

/// Targets de sandbox: **solo** bajo `{app_data_dir}/exported/`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../apps/desktop/src/types/generated/")]
pub enum SandboxTarget {
    Hyprland,
    Waybar,
    Rofi,
}

/// Solicitud de escritura.
///
/// `content` debe ser generado por un adapter (no input directo arbitrario).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WriteRequest {
    pub target: WriteTarget,
    pub content: String,
}

/// Resultado de una escritura exitosa.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../apps/desktop/src/types/generated/")]
pub struct WriteResult {
    /// Ruta absoluta del archivo escrito.
    pub target_path: String,
    /// En sandbox siempre es `None` (no hay backups en esta fase).
    pub backup_path: Option<String>,
}

/// Estado del setup de Hyprland respecto al include gestionado por LCC.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../apps/desktop/src/types/generated/")]
#[serde(tag = "type")]
pub enum HyprlandSetupState {
    /// M-1: include gestionado presente y correcto en el archivo principal.
    ManagedIncludePresent,
    /// M-2: include ausente pero el archivo principal existe y es reparable automáticamente.
    ManagedIncludeAbsent,
    /// M-3: el archivo principal parece haber sido generado completamente por una versión antigua
    /// de la app (contiene el marcador "Generated by Linux Control Center").
    LegacyGeneratedDetected,
    /// M-4: setup no estándar (symlink fuera de HOME, permisos no accesibles, etc.).
    NonStandardSetup { reason: String },
    /// El archivo principal de Hyprland no existe en la ruta esperada.
    MainFileNotFound,
}

/// Estado completo de migración de Hyprland, devuelto por `inspect_hyprland_setup`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export, export_to = "../../../apps/desktop/src/types/generated/")]
pub struct HyprlandMigrationStatus {
    pub state: HyprlandSetupState,
    pub main_config_exists: bool,
    /// Basenames de archivos `.bak.*` del principal en `~/.config/hypr/`.
    pub available_backups: Vec<String>,
    /// `true` solo para `ManagedIncludeAbsent`; indica que la app puede reparar sin confirmación.
    pub can_auto_repair: bool,
    /// Avisos no bloqueantes (e.g. backups no encontrados, permisos limitados).
    pub warnings: Vec<String>,
}

#[derive(Debug, thiserror::Error)]
pub enum HelperError {
    #[error("empty content is not allowed")]
    EmptyContent,

    #[error("content exceeds size limit ({0} bytes > {1} bytes)")]
    ContentTooLarge(usize, usize),

    #[error("resolved path is not under HOME: {0}")]
    PathConfinementViolation(std::path::PathBuf),

    #[error("home directory could not be determined")]
    HomeDirUnknown,

    #[error("invalid backup file name: {0}")]
    InvalidBackupName(String),

    /// Intentar usar `execute_write` con `WriteTarget::HyprlandMainConfig` está prohibido.
    /// La única operación permitida sobre el archivo principal es la inserción idempotente
    /// del include gestionado via `ensure_hyprland_main_sources_lcc_include()`.
    #[error("writing to hyprland.conf via execute_write is forbidden; use ensure_hyprland_main_sources_lcc_include() for the managed include")]
    HyprlandMainConfigWriteForbidden,

    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
}

